# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
    -   id: black
        args: [--safe, --line-length=100]
    -   id: black-jupyter
        args: [--safe, --line-length=100]
        language_version: python3.11

-   repo: https://github.com/pycqa/docformatter
    rev: v1.7.7
    hooks:
    -   id: docformatter
        additional_dependencies: [tomli]
        args: [--config, pyproject.toml]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML, types-tqdm]

-   repo: https://github.com/pycqa/doc8
    rev: v2.0.0
    hooks:
    -   id: doc8
        files: ^docs/.*\.(rst|md)$
        args: [--ignore, D001]

-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8

ci:
    autoupdate_schedule: weekly
