# .readthedocs.yml

# Required
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  image: latest

python:
  version: "3.8"
  find-links:
    - https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
  install:
    - requirements: docs/requirements-docs.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .

formats:
  - htmlzip
  - epub
